name: ✅Build Status Check


env:
  NET_SDK_VERSION: 7.0


on:
  workflow_dispatch:
  pull_request:
    branches:
    - develop
    - master
    - release/v*.*.*
    - preview/v*.*.*-preview.*


jobs:
  determine_build_config:
    name: Determine Build Configuration
    runs-on: ubuntu-latest
    outputs:
      build-config: ${{ steps.get-build-config.outputs.build-config }}
    steps:
      - name: Get Build Config
        id: get-build-config
        shell: pwsh
        run: |
          # If the destination branch that the pull request is merging into is the master, do a release build
          if ( "${{ github.base_ref }}" -eq "master") {
            "build-config=Release" >> $env:GITHUB_OUTPUT;
          } else { # Any other branch than master, do a debug build
            "build-config=Debug" >> $env:GITHUB_OUTPUT;
          }


  get_sdk_version:
    name: Get SDK Version
    runs-on: ubuntu-latest
    outputs:
      sdk-version: ${{ steps.get-sdk-version.outputs.sdk-version }}
    steps:
      - name: Get SDK Version From Environment Variable
        id: get-sdk-version
        shell: pwsh
        run: |
          "sdk-version=${{ env.NET_SDK_VERSION }}" >> $env.GITHUB_OUTPUT;


  build_project:
    name: Build Project
    needs: [determine_build_config, get_sdk_version]
    uses: KinsonDigital/Infrastructure/.github/workflows/build-csharp-project.yml@v3.0.2
    with:
      project-name: "Partithyst"
      build-config: ${{ needs.determine_build_config.outputs.build-config }}
      net-sdk-version: ${{ needs.get_sdk_version.outputs.sdk-version }}


  build_test_project:
    name: Build Test Project
    needs: [determine_build_config, get_sdk_version]
    uses: KinsonDigital/Infrastructure/.github/workflows/build-csharp-project.yml@v3.0.2
    with:
      project-name: "PartithystTests"
      build-config: ${{ needs.determine_build_config.outputs.build-config }}
      net-sdk-version: ${{ needs.get_sdk_version.outputs.sdk-version }}
